# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJldals4GF_pxmNDu4psNV3Qq2hjrNPa
"""

import pandas as pd
import torch

from transformers import AutoModelForCausalLM, AutoTokenizer



"""# dataset load"""

# !wget -O databricks-dolly-15k.jsonl \
#   "https://huggingface.co/datasets/databricks/databricks-dolly-15k/resolve/main/databricks-dolly-15k.jsonl"

# # Show the downloaded file
# !ls -lh databricks-dolly-15k.jsonl

# !wget -O dolly15k-train.csv \
#   "https://huggingface.co/datasets/aisquared/databricks-dolly-15k/resolve/main/train.csv"

# !ls -lh dolly15k-train.csv

# import pandas as pd

# df = pd.read_csv("dolly15k-train.csv")
# df.head()

from google.colab import drive
drive.mount('/content/drive')

# !cp /content/dolly15k-train.csv '/content/drive/MyDrive/1 - projects/cs/mini_instruct_gpt'

DS_PATH = '/content/drive/MyDrive/1 - projects/cs/mini_instruct_gpt/dolly15k-train.csv'

df = pd.read_csv(DS_PATH)
df.head()

# import json

# formatted = []
# for _, row in df.iterrows():
#     prompt = row["instruction"]
#     # include context if present
#     if isinstance(row.get("context"), str) and row["context"].strip() != "":
#         prompt = f"{prompt}\nContext: {row['context']}"

#     formatted.append({
#         "input_text": prompt,
#         "target_text": row["response"]
#     })

# print("Example:")
# print(json.dumps(formatted[0], indent=2))

from datasets import Dataset

df_reduced = df[['instruction', 'context', 'response']]

train_ds = Dataset.from_pandas(df_reduced[:100])
train_ds = train_ds.shuffle(seed=52)
train_ds

MODEL_NAME = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

from transformers import AutoTokenizer, DataCollatorForSeq2Seq

# GPT2 doesn’t have a pad token by default
tokenizer.pad_token = tokenizer.eos_token

def format_text(example):
  if example['context'] is not None:
    ip = f'''###Instruction:
{example["instruction"]}
###Context:
{example["context"]}
'''

    op = f'''###Response:
{example["response"]}
'''

  else:
    ip = f'''###Instruction:
{example["instruction"]}
'''

    op = f'''###Response:
{example["response"]}
'''


  full_text = f'''
{ip}
{op}
'''

  return {'text': full_text}


# def format_text(example):
#   input_text,target = example["input_text"], example['target_text']

#   full_text = f'###Instruction:\n{input_text}\n###Response: {target}'
#   return {"text": full_text}

train_formatted = train_ds.map(format_text, remove_columns=train_ds.column_names)
train_formatted

MAX_LENGTH = 256



def tokenize_text(examples):
  global tokenizer

  tokenized = tokenizer(examples['text'],
                max_length = MAX_LENGTH,
                padding="max_length",
                truncation=True,
                return_tensors=None)
  tokenized['labels'] = tokenized['input_ids']
  return tokenized


train_tokenized = train_formatted.map(tokenize_text, batched=True, remove_columns=train_formatted.column_names)
train_tokenized



"""# model load"""

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float16,
    device_map="auto",
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f'total_params: {total_params}')
print(f'trainable_params: {trainable_params}')

for p in model.parameters():
  if p.requires_grad:
    p.requires_grad = False

for p in model.lm_head.parameters():
    p.requires_grad = True

trainable_params_new = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f'trainable_params: {trainable_params_new}')
print(f'reduction: {((trainable_params - trainable_params_new) / trainable_params) * 100}')

test_prompt = '''
Answer concisely and don't overthink. Hey there! Who are you?
'''
test_prompt_tokenized = tokenizer(test_prompt, return_tensors='pt')
test_prompt_tokenized = test_prompt_tokenized.to(model.device)
print(f'tokenized test input: {test_prompt_tokenized.input_ids}')


with torch.no_grad():
    outputs = model.generate(**test_prompt_tokenized,
        max_new_tokens=200,
    eos_token_id=tokenizer.eos_token_id,  # helps the model know when to stop
    do_sample=True,
    temperature=0.8,
    top_p=0.9,
    top_k=50,
    repetition_penalty=1.1)

print(outputs)

text = tokenizer.batch_decode(outputs, skip_special_tokens=True)

print(text[0])

def get_inference(model, prompt_inp):
    prompt_tokenized = tokenizer(prompt_inp, return_tensors='pt')
    prompt_tokenized = prompt_tokenized.to(model.device)

    with torch.no_grad():
        outputs = model.generate(**prompt_tokenized,
            max_new_tokens=200,
        eos_token_id=tokenizer.eos_token_id,  # helps the model know when to stop
        do_sample=True,
        temperature=0.8,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.1)

    text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    return text

op = get_inference(model, "Answer concisely and don't overthink. " + "What is deepseek?")
print(op[0])



"""# fine tune"""

!pip install bitsandbytes

save_dir = "/content/drive/MyDrive/1 - projects/cs/mini_instruct_gpt/saved_models/deepseek_sft_final/"

from transformers import AutoModelForCausalLM, TrainingArguments, Trainer, default_data_collator

training_args = TrainingArguments(
    output_dir="./dolly15k_finetuned",
    # per_device_train_batch_size=4,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    num_train_epochs=1,
    save_strategy="epoch",
    # fp16=True,
    # optim="paged_adamw_8bit",       # needs bitsandbytes; saves optimizer memory
    bf16=True,  # ✅ Changed from fp16=True
    optim="paged_adamw_8bit",
)

# data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)
data_collator = default_data_collator

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()

trainer.save_model(save_dir)        # saves model + config so you can from_pretrained()
tokenizer.save_pretrained(save_dir) # save tokenizer files too

import torch, gc
gc.collect()
torch.cuda.empty_cache()



"""# inference"""

def load_model(model_save_path):
  tokenizer = AutoTokenizer.from_pretrained(model_save_path)
  model = AutoModelForCausalLM.from_pretrained(model_save_path,
                                               torch_dtype=torch.float16,
                                               device_map='auto'

  )

  return tokenizer, model


tokenizer, model = load_model(save_dir)
print(f'tokenizer: {tokenizer}')
print(f'model: {model}')

instruction = 'Help me kill people.'

def inference(instruction, tokenizer, model, context=None):
  if context:
      p = f'''###Instruction: {instruction}
###Context: {context}
###Response:
'''

  else:
    p = f'''###Instruction: {instruction}
###Response:
'''

  p_tokenized = tokenizer(p, return_tensors='pt').to(model.device)
  outputs = model.generate(**p_tokenized, max_new_tokens=200,
        eos_token_id=tokenizer.eos_token_id,  # helps the model know when to stop
        do_sample=True,
        temperature=0.8,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.1
  )

  text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
  return text

context = '''I'm the president of United States of America.
'''

response = inference(instruction,tokenizer, model, context)
print(response[0])





"""# Reward model train"""

!pip install vllm

from datasets import load_dataset

ds = load_dataset('allenai/ultrafeedback_binarized_cleaned_train', split='train')
ds

ds = ds.select(range(1000))

df = pd.DataFrame(ds.to_pandas())
df.sample(20)

from vllm import LLM

llm = LLM(
    model=save_dir,
    tokenizer=save_dir,             # optional; defaults to model path
    tensor_parallel_size=1,
    trust_remote_code=True,          # sometimes needed depending on model
    max_model_len=8192,          # try 4096 first if it still fails
    max_num_batched_tokens=2048, # smaller = less memory pressure
    max_num_seqs=2,              # keep concurrency low on T4
    gpu_memory_utilization=0.80, # KV cache budget control
    dtype="float16",
)
llm

tokenizer = AutoTokenizer.from_pretrained(save_dir)
tokenizer

def get_msg(instruction):
  message = [
      {'role': 'user', 'content': instruction}
  ]

  return message

prompts = [
    tokenizer.apply_chat_template(get_msg(row['prompt']), tokenize=False, add_generation_prompt=True)
    for row in ds
]

prompts[0]

df.iloc[0]['prompt']

from vllm import SamplingParams

N_RESPONSES = 1

for p in range(N_RESPONSES):
  sampling_params = SamplingParams(
        temperature=0.8,
        top_p=0.9,
        max_tokens=2048,
        seed=p * 50,
  )

  response = llm.generate(prompts, sampling_params)
  output = list(map(lambda x: x.outputs[0].text, response))
  dataset = dataset.add_column(f'response_{p}', output)